# | Config-Version: 1.0
# [̲̲̅̅C̲̲̅̅o̲̲̅̅n̲̲̅̅f̲̲̅̅i̲̲̅̅g̲̲̅̅u̲̲̅̅r̲̲̅̅a̲̲̅̅t̲̲̅̅i̲̲̅̅o̲̲̅̅n̲̲̅̅s̲̲̅̅]
config:
  debug: false
items:
  worlds:
    - world
    - spawn
format:
  perm: '§cFehlende Berechtigung §a>> $6%wp-args%'
  help:
    default: '§e/%wp-args% <Command>'
    spawn: '§e/%wp-args% spawn <Prefab> <Spieler> <Anzahl>'
  disabledworld: '$cDas Prefab-System ist für diese Welt deaktiviert!'
  cooldown: 'Du hast noch einen Cooldown von §6%wp-args%§r Sekunden!'